"""Update table

Revision ID: 17a11ecfc5ee
Revises: 754c50c68ef8
Create Date: 2023-10-29 01:10:29.623818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17a11ecfc5ee'
down_revision = '754c50c68ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gh_username', sa.String(length=255), nullable=False))
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('gh_username')

    # ### end Alembic commands ###
