"""update table

Revision ID: 1ac338f4cead
Revises: c943c9418454
Create Date: 2023-10-28 23:33:18.829684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ac338f4cead'
down_revision = 'c943c9418454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('github_data', schema=None) as batch_op:
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
