"""Update table

Revision ID: 754c50c68ef8
Revises: 1ac338f4cead
Create Date: 2023-10-28 23:45:52.563310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '754c50c68ef8'
down_revision = '1ac338f4cead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=255), nullable=False))
        batch_op.drop_column('search_query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_query', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
