"""Add active field to the user model

Revision ID: 880af07b2f51
Revises: 99ebd1e2e15d
Create Date: 2023-10-25 23:31:08.404691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880af07b2f51'
down_revision = '99ebd1e2e15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
